spring:
  datasource:
    username: ecommerce_user
    url: jdbc:mysql://localhost:3306/ecommerce_db
    password: userpassword
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    open-in-view: false

  jms:
    pub-sub-domain: false  # Set to ''true'' for topics, ''false'' for queues
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616


jwt:
  secret:
    key: abcdefghijklmnopqrstuvwxyz123456
  expiration:
    time: 43200000
