global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['e-commerce-app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']