global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'  # Spring Boot metrics endpoint
    static_configs:
      - targets: ['e-commerce-app:8080']  # Replace with the service name and port
